#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_tekton="tekton"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

PURGE=false
# get the options
while getopts ":p" flag; do
  case "${flag}" in
          p) PURGE=true
             ;;
          *) echo "Usage: microk8s disable tekton [-p]"
             echo ""
             echo "WARNING: Final deletion of \"$NAMESPACE_tekton\" namespace must be enforced by: \"microk8s disable tekton -p\""
             echo ""
             echo "Purge only when sure, that \"$NAMESPACE_tekton\" namespace is not hosting any other services from Argo stack."
             echo ""
             exit 0
             ;;
  esac
done

echo "Disabling tekton"

$HELM delete argo-cd -n $NAMESPACE_tekton

$KUBECTL delete customresourcedefinition applications.argoproj.io \
                applicationsets.argoproj.io \
                tektonextensions.argoproj.io  \
                appprojects.argoproj.io

if $PURGE; then
    echo "Final \"$NAMESPACE_tekton\" namespace deletion"
    $KUBECTL delete $KUBECTL_DELETE_ARGS namespace "$NAMESPACE_tekton" > /dev/null 2>&1 || true
else
    echo ""
    echo "WARNING: Final deletion of \"$NAMESPACE_tekton\" namespace must be enforced by: \"microk8s disable tekton -p\""
    echo ""
    echo "Purge only when sure, that \"$NAMESPACE_tekton\" namespace is not hosting any other services from Argo stack."
    echo ""
fi

echo "tekton disabled"