#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_tekton="tekton-operator"

tekton_HELM_VERSION="0.64.0"

"$SNAP/microk8s-enable.wrapper" helm

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm.wrapper"
GIT_EXEC_PATH=/snap/microk8s/current/usr/lib/git-core/
VALUES=""

# get the options
while getopts ":v:f:h:" flag; do
  case "${flag}" in
          v) tekton_HELM_VERSION=${OPTARG}
             ;;
          f) VALUES=${OPTARG}
             ;;
          *) echo "Usage: microk8s enable tekton"
             echo ""
             echo "With overwriting default values: microk8s enable tekton -f values.yaml"
             echo ""
             echo "See https://cdfoundation.github.io/tekton-helm-chart for more information about the values"
             echo "You should enable the Ingress addon, if you want to use tekton with an Ingress"
             echo "microk8s enable ingress"
             exit 0
             ;;
  esac
done

echo "Installing tekton (Helm v${tekton_HELM_VERSION})"

if [ -n "$VALUES" ]; then
    echo "Using values file: $VALUES"
fi

# add the tekton chart repository
export GIT_EXEC_PATH=/snap/microk8s/current/usr/lib/git-core/
$HELM plugin remove helm-git > /dev/null 2>&1 || true
$HELM plugin install https://github.com/aslafy-z/helm-git --version 1.3.0
$HELM repo add tektoncd git+https://github.com/tektoncd/operator@charts?ref=main

# install the helm chart
if [ -z "$VALUES" ]
then
    $HELM upgrade -i tekton-operator \
      --create-namespace \
      --set installCRDs=true \
      --version $tekton_HELM_VERSION \
      --namespace "$NAMESPACE" \
      tektoncd/tekton-operator
else
    $HELM upgrade -i tekton-operator \
      --version $tekton_HELM_VERSION \
      --create-namespace \
      --namespace "$NAMESPACE" \
      -f $VALUES \
      tektoncd/tekton-operator
fi

echo "Tekton is installed"