#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE_tekton="tekton-operator"

tekton_HELM_VERSION="0.64.0"

"$SNAP/microk8s-enable.wrapper" helm3

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
HELM="$SNAP/microk8s-helm3.wrapper"
GIT="$SNAP/usr/bin/git"

VALUES=""

# get the options
while getopts ":v:f:h:" flag; do
  case "${flag}" in
          v) tekton_HELM_VERSION=${OPTARG}
             ;;
          f) VALUES=${OPTARG}
             ;;
          *) echo "Usage: microk8s enable tekton"
             echo ""
             echo "With overwriting default values: microk8s enable tekton -f values.yaml"
             echo ""
             echo "See https://cdfoundation.github.io/tekton-helm-chart for more information about the values"
             echo "You should enable the Ingress addon, if you want to use tekton with an Ingress"
             echo "microk8s enable ingress"
             exit 0
             ;;
  esac
done

echo "Installing tekton (Helm v${tekton_HELM_VERSION})"

if [ -n "$VALUES" ]; then
    echo "Using values file: $VALUES"
fi

# add the tekton chart repository
unset GTK_PATH
$GIT clone https://github.com/tektoncd/operator.git
$HELM repo add tektoncd https://kubebb.github.io/components

# install the helm chart
if [ -z "$VALUES" ]
then
    $HELM upgrade -i tekton-operator \
      --create-namespace \
      --set installCRDs=true \
      --version $tekton_HELM_VERSION \
      --namespace "$NAMESPACE" \
      ./operator/chart
else
    $HELM upgrade -i tekton-operator \
      --version $tekton_HELM_VERSION \
      --create-namespace \
      --namespace "$NAMESPACE" \
      -f $VALUES \
      ./operator/chart
fi

echo "Tekton is installed"